"""Adds is_deleted field to blogs db

Revision ID: 9112ea95fdaf
Revises: 6352dcf47494
Create Date: 2024-02-18 03:26:56.841944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9112ea95fdaf'
down_revision: Union[str, None] = '6352dcf47494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'is_deleted')
    # ### end Alembic commands ###
